version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: makeslidev-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: makeslidev123
      MONGO_INITDB_DATABASE: makeslidev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - makeslidev-network

  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: makeslidev-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8080
      MONGODB_URI: mongodb://admin:makeslidev123@mongodb:27017/makeslidev?authSource=admin
      MONGO_PRIVATE_URL: mongodb://admin:makeslidev123@mongodb:27017/makeslidev?authSource=admin
      JWT_SECRET: makeslidev-jwt-secret-change-in-production
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - ./backend/public:/app/public:ro
    networks:
      - makeslidev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Next.js Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://localhost:8080
        NEXT_PUBLIC_APP_URL: http://localhost:3000
    container_name: makeslidev-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8080
      NEXT_PUBLIC_APP_URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - makeslidev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local

networks:
  makeslidev-network:
    driver: bridge
